# Generated by Django 3.1.7 on 2021-04-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='mobile',
            new_name='phone',
        ),
    ]
